<p>

<form name="search" action="searchresult.asp" method="post">

<div class="row">

<div class="col-sm-8"></div>

<div class="col-sm-2"><input type="text" name="txtmodel"></div>

<div class="col-sm-2"><input type="submit" name="action_button" value="  產品名稱  "></div>

</div>  

</form> 

</p>
            
<div class="alert alert-success">

<div class="row">

<div class="col-sm-3"><h3>享基</h3></div>

<div class="col-sm-6"></div>

<div class="col-sm-3"><h3>Enhance Technologies</h3></div>

</div>

<div class="row">

<div class="col-sm-6"></div>

<div class="col-sm-2"><h6><a href="mailto:info@enhance-tech.com.hk">info@enhance-tech.com.hk</a></h6></div>

<div class="col-sm-2"><h6>電話: +86-769-82052036</h6></div>

<div class="col-sm-2"><h6>手機: +86-133 8019 4136</h6></div>

</div>                                        
          
</div>   

<! -- Navigatiion Bar -->

<nav class="navbar navbar-default">

  <div class="container-fluid">

    <ul class="nav navbar-nav">

      <li > <a href="default.asp">主頁</a></li>

      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">模具標準件</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=2&action_button=category">Opitz 日期章(日字嘜)</a></li>

          <li><a href="searchresult.asp?selcategory=1&action_button=category">WEMA 標準件</a></li>
          
        </ul>

      </li>

        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">高壓短衝程油缸</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=3&action_button=category">VEGA 系列</a></li>

          <li><a href="searchresult.asp?selcategory=4&action_button=category">VENNI 系列</a></li>
          
        </ul>

      </li>

 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">加熱器及配件</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=6&action_button=category">GC-Heat 系列</a></li>

          <li><a href="searchresult.asp?selcategory=7&action_button=category">HotSet 系列</a></li>

          <li><a href="searchresult.asp?selcategory=43&action_button=category">WEMA 系列</a></li>
    
          <li><a href="searchresult.asp?selcategory=47&action_button=category">Graff 系列</a></li>
    
          
        </ul>

      </li>

 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">溫度控制系統</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=8&action_button=category">ALTAMIUM 系列</a></li>

          <li><a href="searchresult.asp?selcategory=9&action_button=category">EUROTHERM 系列</a></li>
          
          <li><a href="searchresult.asp?selcategory=10&action_button=category">Korea Digital 系列</a></li>

          <li><a href="searchresult.asp?selcategory=44&action_button=category">Hotset 系列</a></li>

          <li><a href="searchresult.asp?selcategory=45&action_button=category">WEMA 系列</a></li>
        
        </ul>

      </li>

 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">交鑰匙解決方案</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=13&action_button=category">物料輸送</a></li>

          <li><a href="searchresult.asp?selcategory=15&action_button=category">高光模具快速加熱</a></li>
          
        </ul>

      </li>

<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">熱流遁系統</a>

        <ul class="dropdown-menu">

          <li><a href="searchresult.asp?selcategory=11&action_button=category">LSR 冷流道系統</a></li>

          <li><a href="searchresult.asp?selcategory=12&action_button=category">熱流道系統</a></li>
          
        </ul>

      </li>

      <li><A href="searchresult.asp?selcategory=46&action_button=category">其它器材</A></li>

      <li><a href="profile.asp">公司資料</a></li>

      <li><a href="contact.asp">聯絡我們</a></li>

      <li><a href="login.asp">分銷商登入</a></li>

      
   

    </ul>

  </div>

</nav>        
  




 
