        </TR>
        <TR>
          <TD><IMG height=40 alt="" 
            src="images/space.gif" 
      border=0></TD></TR></TBODY></TABLE></TD>
    <TD bgColor=#e41f1f><IMG height=1 alt="" 
      src="images/space.gif" width=1 border=0></TD></TR>
  <TR>
    <TD bgColor=#e41f1f><IMG height=1 alt="" 
      src="images/space.gif" width=1 border=0></TD>
    <TD vAlign=top align=middle bgColor=#ffffff><!-- bottom nav shopping include --><!-- footer -->
      <TABLE cellSpacing=0 cellPadding=0 width=758 border=0>
        <TBODY>
        <TR>
          <TD><IMG height=1 alt="" src="images/space.gif" 
            width=13 border=0></TD>
          <TD height=12><A href="snew_c.asp">最新產品</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A href="offer_c.asp">特別推介
</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A href="Catalog_c.asp">產品目錄</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A href="searchresult_c.asp?action_button=model">產品資料</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A href="tradeshow_c.asp">展覽資料</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A href="newsletter_c.asp">公司新聞</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A 
            href="enquiry_c.asp">查諮詢籃</A></TD>
          <TD><IMG height=12 alt="" 
            src="images/nav_divider.gif" width=19 
border=0></TD>
          <TD><A 
            href="order_c.asp">查樣板籃</A></TD>
          <TD></TD>
          <TD><IMG height=1 alt="" src="images/space.gif" 
            width=35 border=0></TD></TR></TBODY></TABLE></TD>
    <TD bgColor=#e41f1f><IMG height=1 alt="" 
      src="images/space.gif" width=1 border=0></TD></TR>
  <TR>
    <TD bgColor=#e41f1f><IMG height=1 alt="" 
      src="images/space.gif" width=1 border=0></TD>
    <TD bgColor=#ffffff><IMG height=5 alt="" 
      src="images/space.gif" width=1 border=0></TD>
    <TD bgColor=#e41f1f><IMG height=1 alt="" 
      src="images/space.gif" width=1 border=0></TD></TR>
  <TR>
    <TD bgColor=#e41f1f colSpan=3><IMG height=1 alt="" 
      src="images/space.gif" width=1 
border=0></TD></TR></TBODY></table>