<SCRIPT language=JavaScript>
<!--
	var garyMenuData = new Array()
	var garyMenuNames = new Array()
	garyMenuData["multifunction"] = new Array()
	garyMenuNames.push( new Array("multifunction", 15, 15, 89, 65, 15, 69) )
	garyMenuData["multifunction"].push( new Array("Browse All","searchresult.asp?selcategory=41&action_button=category") )

	garyMenuData["metal"] = new Array()
	garyMenuNames.push( new Array("metal", 120, 120, 170, 138, 120, 141) )
	garyMenuData["metal"].push( new Array("Browse All","searchresult.asp?subcategory=metal&action_button=subcategory") )
	garyMenuData["metal"].push( new Array("Ball Pen","searchresult.asp?selcategory=24&action_button=category") )
	garyMenuData["metal"].push( new Array("Fountain Pen","searchresult.asp?selcategory=22&action_button=category") )
	garyMenuData["metal"].push( new Array("Pencil","searchresult.asp?selcategory=39&action_button=category") )
	garyMenuData["metal"].push( new Array("Pen set","searchresult.asp?selcategory=49&action_button=category") )
	garyMenuData["metal"].push( new Array("Roller Pen","searchresult.asp?selcategory=25&action_button=category") )
	
	garyMenuData["plastic"] = new Array()
	garyMenuNames.push( new Array("plastic", 182, 182, 170, 138, 182, 141) )
	garyMenuData["plastic"].push( new Array("Browse All","searchresult.asp?subcategory=plastic&action_button=subcategory") )
	garyMenuData["plastic"].push( new Array("Ball Pen","searchresult.asp?selcategory=23&action_button=category") )
	garyMenuData["plastic"].push( new Array("Fountain Pen","searchresult.asp?selcategory=53&action_button=category") )
	garyMenuData["plastic"].push( new Array("Pencil","searchresult.asp?selcategory=54&action_button=category") )
	garyMenuData["plastic"].push( new Array("Pen Set","searchresult.asp?selcategory=50&action_button=category") )
	garyMenuData["plastic"].push( new Array("Roller Pen","searchresult.asp?selcategory=52&action_button=category") )



	garyMenuData["wooden"] = new Array()
	garyMenuNames.push( new Array("wooden", 255, 255, 173, 140, 255, 144) )
	garyMenuData["wooden"].push( new Array("Browse All","searchresult.asp?subcategory=wooden&action_button=subcategory") )
	garyMenuData["wooden"].push( new Array("Ball Pen","searchresult.asp?selcategory=43&action_button=category") )
	garyMenuData["wooden"].push( new Array("Fountain Pen","searchresult.asp?selcategory=45&action_button=category") )
	garyMenuData["wooden"].push( new Array("Pencil","searchresult.asp?selcategory=55&action_button=category") )
	garyMenuData["wooden"].push( new Array("Pen Set","searchresult.asp?selcategory=51&action_button=category") )
	garyMenuData["wooden"].push( new Array("Roller Pen","searchresult.asp?selcategory=44&action_button=category") )

	garyMenuData["led"] = new Array()
	garyMenuNames.push( new Array("led", 350, 350, 172, 138, 350, 142) )
	garyMenuData["led"].push( new Array("Browse all","searchresult.asp?subcategory=led&action_button=model") )
	garyMenuData["led"].push( new Array("Key Chain","searchresult.asp?selcategory=46&action_button=category") )
	garyMenuData["led"].push( new Array("UV Light","searchresult.asp?selcategory=58&action_button=category") )
	garyMenuData["led"].push( new Array("Pen","searchresult.asp?selcategory=60&action_button=category") )

	garyMenuData["packaging"] = new Array()
	garyMenuNames.push( new Array("packaging", 420, 421, 185, 153, 421, 157) )
	garyMenuData["packaging"].push( new Array("Browse all","searchresult.asp?subcategory=packaging&action_button=subcategory") )
	garyMenuData["packaging"].push( new Array("Metal Material","searchresult.asp?selcategory=42&action_button=category") )
	garyMenuData["packaging"].push( new Array("Cardboard Material","searchresult.asp?selcategory=56&action_button=category") )
	garyMenuData["packaging"].push( new Array("Plastic Material","searchresult.asp?selcategory=40&action_button=category") )
	garyMenuData["packaging"].push( new Array("Wooden Material","searchresult.asp?selcategory=57&action_button=category") )


/*
	garyMenuData["Top Picks"] = new Array()
	garyMenuNames.push( new Array("Top Picks", 499, 497, 157, 105, 497, 109) )

*/

 garyMenuData["price"] = new Array()
	garyMenuNames.push( new Array("price", 649, 649, 157, 110, 649, 110) )
	garyMenuData["price"].push( new Array("Below USD 0.50/PC","searchresult.asp?selexprice=77&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD0.50 - 1.0/PC","searchresult.asp?selexprice=78&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD1.0 - 2.0/PC","searchresult.asp?selexprice=80&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD2.0 - 3.0/PC","searchresult.asp?selexprice=81&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD3.0 - 5.0/PC","searchresult.asp?selexprice=79&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD5.0 - 8.0/PC","searchresult.asp?selexprice=82&action_button=exprice") )
	garyMenuData["price"].push( new Array("USD8.0 or above","searchresult.asp?selexprice=83&action_button=exprice") )




//-->
</SCRIPT>
