<p>

<div class="row">

<div class="col-sm-2"></div>

<div class="col-sm-2"><A href="offer.asp">特別優惠</A></div>

<div class="col-sm-2"></div>
         
<div class="col-sm-2"><A href="request.asp">詢價清單</A></div>

<div class="col-sm-2"></div>
       
<div class="col-sm-2"><A href="order.asp">購物清單</A></div>
      
</div>

</p>

<p>

<div class="row">

<div class="col-sm-3"></div>

<div class="col-sm-9"><h6>享基科技有限公司 Copyright 2009. Enhance Technologies Limited. All right reserved.</h6></div>

</div>

</p>